<?php
    return [
        [
            'title' => 'Dashboard',
            'route' => 'dashboard',
            'icon' => 'bi-speedometer2',
            'active' => 'dashboard',
            
        ],
        [
            'title' => 'Employees',
            'route' => 'employees.index',
            'icon' => 'bi-people',
            'ability' => 'viewAny',
            'active' => 'employees.*',
            'model' => \App\Models\Employee::class,
        ],
        [
            'title' => 'My Profile',
            'route' => 'employees.show',
            'route_params' => fn() => auth()->id(),
            'icon' => 'bi-person-circle',
            'ability' => 'viewOwn',
            'active' => 'employees.show',
            'model' => \App\Models\Employee::class,
        ],
        
        [
            'title' => 'Departments',
            'route' => 'departments.index',
            'icon' => 'bi-building',
            'ability' => 'viewAny',
            'active' => 'departments.*',
            'model' => \App\Models\Department::class,
        ],
        [
            'title' => 'My Department',
            'route' => 'departments.show',
            'route_params' => fn() => auth()->user()->department_id,
            'icon' => 'bi-building-check',
            'ability' => 'viewOwn',
            'active' => 'departments.show',
            'model' => \App\Models\Department::class,
        ],
        [
            'title' => 'Payrolls',
            'route' => 'payrolls.index',
            'icon' => 'bi-currency-dollar',
            'ability' => 'viewAny',
            'active' => 'payrolls.*',
            'model' => \App\Models\Payroll::class,
        ],
        [
            'title' => 'Attendance',
            'route' => 'attendance.index',
            'icon' => 'bi-calendar-check',
            'ability' => 'viewAny',
            'active' => 'attendance.*',
            'model' => \App\Models\Attendance::class,
        ],
        [
            'title' => 'Leaves',
            'route' => 'leave-requests.index',
            'icon' => 'bi-card-checklist',
            'ability' => 'viewAny',
            'active' => 'leave-requests.*',
            'model' => \App\Models\LeaveRequest::class,
        ],
        [
            'title' => 'Leave Types',
            'route' => 'leave_types.index',
            'icon' => 'bi-tags',
            'ability' => 'viewAny',
            'active' => 'leave_types.*',
            'model' => \App\Models\LeaveType::class,
        ],
        [
            'title' => 'Tasks',
            'route' => 'tasks.index',
            'icon' => 'bi-list-task',
            'ability' => 'viewAny',
            'active' => 'tasks.*',
            'model' => \App\Models\Task::class,
        ],
        [
            'title' => 'Roles',
            'route' => 'roles.index',
            'icon' => 'bi-shield-lock',
            'ability' => 'viewAny',
            'active' => 'roles.*',
            'model' => \App\Models\Role::class,
        ],
        [
            'title' => 'Reports',
            'route' => 'reports.index',
            'icon' => 'bi-bar-chart',
            'ability' => 'viewAny',
            'active' => 'reports.*',
            'model' => App\Models\Report::class,
        ],
    ];